### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by PrasBiswas2016** [mkroli/karaf-docker#2]
I got it running,....but what does it actually do?

**Comment by mkroli** [comment]
Please have a look at http://karaf.apache.org/manual/latest/#_overview

**Comment by PrasBiswas2016** [comment]
Yes I am familiar with Karaf. 

My question is - how to access Karaf over Docker?

What **protocol://url:port** should I use?

**Comment by PrasBiswas2016** [comment]
This is the answer:

	 docker run -it mkroli/karaf:latest

Use the **-it** switch to enter Interactively in shell mode - starts the container in interactive mode so that Ctrl-C/D and the shell function properly

**Comment by mkroli** [comment]
Another option would be ssh. So after starting like this:
```
docker run -d --name karaf -p 8101:8101 mkroli/karaf:latest
```
you can ssh into it:
```
ssh -p8101 karaf@localhost
```
