### ISSUE TITLE
How to install features using Dockerfile

### ISSUE THREAD

**Issue by imranrazakhan** [mkroli/karaf-docker#3]
I am trying to create a Dockerfile that will automatically install karaf and configure it to work. I have all of the steps working except the last piece. I need install a list of features. I can do it if I log in but I try automate the process. What command can I run that will allow me to install the features?

**Comment by mkroli** [comment]
The following worked for me:
```
FROM mkroli/karaf

RUN echo "feature:install webconsole" | /opt/karaf/bin/karaf
```

**Comment by imranrazakhan** [comment]
i am getting following error

Step 14/15 : RUN echo "feature:repo-add camel 2.20.2" | /opt/karaf/bin/karaf
 ---> Running in 346d8d4e6308
        __ __                  ____
       / //_/____ __________ _/ __/
      / ,<  / __ `/ ___/ __ `/ /_
     / /| |/ /_/ / /  / /_/ / __/
    /_/ |_|\__,_/_/   \__,_/_/

  Apache Karaf (4.1.5)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown Karaf.

Error in initialization script: /opt/karaf/etc/shell.init.script: String index out of range: 0
karaf@root()> Command not found: feature:repo-add
karaf@root()> Error executing command: java.lang.NullPointerException
 ---> 0511dd233a6e

**Comment by mkroli** [comment]
Another option would be to configure karaf itself. There is a file located in ```/opt/karaf/etc/org.apache.karaf.features.cfg```. The ```featuresBoot``` setting is a comma separated list of features to be installed during boot. The setting ```featuresRepositories``` is a comma separated list of features repositories to register by default.
