### ISSUE TITLE
Karaf Stop when do CTRL+C

### ISSUE THREAD

**Issue by imranrazakhan** [mkroli/karaf-docker#4]
By using this file as soon as we exit from screen karaf got stop, how we can make it keep running and do ssh to shell on demand?

**Comment by mkroli** [comment]
It should work if you use the ```-d``` flag as follows:
```bash
docker run -d -t \
  --name karaf \
  -p 1099:1099 \
  -p 8101:8101 \
  -p 44444:44444 \
  -v /host/path/deploy:/deploy \
  mkroli/karaf
```
